# Generated by Django 5.1.2 on 2024-11-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/')),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('Career', 'Career')], default='academic', max_length=100)),
            ],
        ),
    ]
