# Generated by Django 5.1.2 on 2024-11-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic'), ('career', 'Career')], default='academic', max_length=100),
        ),
    ]
