# Generated by Django 5.1.2 on 2024-11-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lectures/images/'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='notes',
            field=models.FileField(upload_to='lectures/notes/'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='lectures/videos/'),
        ),
    ]
